name: WebPageTest PROD-env
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest PROD-env
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: WebPageTest
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            https://adventures.polaris.com/
            https://adventures.polaris.com/adventure/snowmobile-rentals-gorham-new-hampshire/
            https://adventures.polaris.com/search?locations=Colorado,%20United%20States&tab=0
            https://adventures.polaris.com/adventure/snowmobile-rentals-silverton-colorado/
          label: 'WebPageTest PROD-env'
          budget: 'wpt-budget.json'
          wptOptions: 'wpt-options.json'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
