name: WebPageTest TEST-env
on:
  workflow_run:
    workflows: ["Workflow Dispatch", "Workflow Dispatch 2"]
    types: [completed] #requested
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest TEST-env
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Test with environment variables
        run: echo $NOW
        env:
          NOW: ${{ steps.date.outputs.date }}
        
      - name: WebPageTest GitHub Action
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            https://adventures:polaris@adventures.polaris-test.run/
          label: '$NOW TEST-env '
          budget: 'wpt-budget.json'
          wptOptions: 'wpt-options.json'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          NOW: ${{ steps.date.outputs.date }}
