on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Action
    steps:        
      - name: WebPageTest
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: 0ca1f42e-87bd-4bde-9dee-c8416ddb7ac4
          urls: |
            https://adventures.polaris.com
          label: 'GitHub Action Test'
