on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: WPT Action (TEST)
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: WebPageTest
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            https://adventures:polaris@adventures.polaris-test.run/
            https://adventures:polaris@adventures.polaris-test.run/our-outfitters/amk-adventures-outfitters/
            https://adventures:polaris@adventures.polaris-test.run/adventure/indysnowexp/
            https://adventures:polaris@adventures.polaris-test.run/search?locations=Minnesota,%20United%20States
          label: 'GitHub Action Test'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
