name: WebPageTest TEST-env
on:
  workflow_run:
    workflows: ["Workflow Dispatch", "Workflow Dispatch 2"]
    types: [completed] #requested
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest TEST-env
    steps:


      - name: Date Actions
        # You may pin to the exact commit or the version.
        # uses: ajilraju/actions-date@4cfac9163870601540ca713c4e51ba65d57e4a06
        uses: ajilraju/actions-date@v0.1
      
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: WebPageTest
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            https://adventures:polaris@adventures.polaris-test.run/
          label: 'WebPageTest TEST-env '
          budget: 'wpt-budget.json'
          wptOptions: 'wpt-options.json'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
