name: WebPageTest TEST-env
on:
  workflow_run:
    workflows: ["Workflow Dispatch", "Workflow Dispatch 2"]
    types: [completed] #requested
  workflow_dispatch:
env:
  DATE: 'Th'

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest TEST-env
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: WebPageTest GitHub Action
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            https://adventures:polaris@adventures.polaris-test.run/
          label: '$DATE TEST-env '
          budget: 'wpt-budget.json'
          wptOptions: 'wpt-options.json'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
